In [18]:
# -*- coding: utf-8 -*-
#向量相加-Python
import sys
from datetime import datetime
import numpy as np

def pythonsum(n):
    a = [i for i in range(n)]
    b = [i for i in range(n)]
    c = []
    for i in range(len(a)):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c

#向量相加-NumPy

def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

#效率比较

size = 1000

start = datetime.now()
c = pythonsum(size)
delta = datetime.now() - start
print ("The last 2 elements of the sum", c[-2:])
print ("PythonSum elapsed time in microseconds", delta.microseconds)

start = datetime.now()
c = numpysum(size)
delta = datetime.now() - start
print ("The last 2 elements of the sum", c[-2:])
print ("NumPySum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [995007996, 998001000]
PythonSum elapsed time in microseconds 3001
The last 2 elements of the sum [995007996 998001000]
NumPySum elapsed time in microseconds 1000


In [13]:
#numpy数组
import numpy as np
a = np.arange(5)
print(a.dtype)
print(a.shape)

int32
(5,)


In [14]:

#创建多维数组
m = np.array([np.arange(2), np.arange(2)])

print (m)

print (m.shape)

print (m.dtype)

np.zeros(10)
np.zeros((3, 6))
np.empty((2, 3, 2))
np.arange(15)

[[0 1]
 [0 1]]
(2, 2)
int32


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
#选取数组元素
a = np.array([[1,2],[3,4]])

print ("In: a")
print (a)

print ("In: a[0,0]")
print (a[0,0])

print ("In: a[0,1]")
print (a[0,1])

print ("In: a[1,0]")
print (a[1,0])

print ("In: a[1,1]")
print (a[1,1])

In: a
[[1 2]
 [3 4]]
In: a[0,0]
1
In: a[0,1]
2
In: a[1,0]
3
In: a[1,1]
4


In [17]:
#numpy数据类型
print ("In: float64(42)")
print (np.float64(42))

print ("In: int8(42.0)")
print( np.int8(42.0))

print ("In: bool(42)")
print (np.bool(42))

print (np.bool(0))

print ("In: bool(42.0)")
print (np.bool(42.0))

print ("In: float(True)")
print (np.float(True))
print (np.float(False))

print ("In: arange(7, dtype=uint16)")
print (np.arange(7, dtype=np.uint16))


print ("In: int(42.0 + 1.j)")
try:
   print(np.int(42.0 + 1.j))
except TypeError:
   print ("TypeError")
#Type error

print ("In: float(42.0 + 1.j)")
print (float(42.0 + 1.j))

In: float64(42)
42.0
In: int8(42.0)
42
In: bool(42)
True
False
In: bool(42.0)
True
In: float(True)
1.0
0.0
In: arange(7, dtype=uint16)
[0 1 2 3 4 5 6]
In: int(42.0 + 1.j)
TypeError
In: float(42.0 + 1.j)


TypeError: can't convert complex to float

In [19]:
# 数据类型转换
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
#数据类型对象
a = np.array([[1,2],[3,4]])

print (a.dtype.byteorder)

print a.dtype.itemsize

In [22]:
#字符编码
import numpy as np
print (np.arange(7, dtype='f'))
print( np.arange(7, dtype='D'))

print (np.dtype(float))

print( np.dtype('f'))
print (np.dtype('d'))
print (np.dtype('f8'))
print (np.dtype('Float64'))

[0. 1. 2. 3. 4. 5. 6.]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]
float64
float32
float64
float64
float64


C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  # This is added back by InteractiveShellApp.init_path()


In [25]:
#dtype类的属性
t = np.dtype('Float64')

print(t.char)

print(t.type)

print(t.str)


d
<class 'numpy.float64'>
<f8


C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  


In [26]:
#创建自定义数据类型
t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])
print( t)

print( t['name'])

itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], dtype=t)

print( itemz[1])

[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')]
<U40
('Butter', 13, 2.72)


In [27]:
#数组与标量的运算
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

1 / arr
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
#一维数组的索引与切片
a = np.arange(9)

print( a[3:7])

print( a[:7:2])

print( a[::-1])

s = slice(3,7,2)
print( a[s])

s = slice(None, None, -1)

print( a[s])


[3 4 5 6]
[0 2 4 6]
[8 7 6 5 4 3 2 1 0]
[3 5]
[8 7 6 5 4 3 2 1 0]


In [29]:
#多维数组的切片与索引
b = np.arange(24).reshape(2,3,4)

print (b.shape)

print (b)

print( b[0,0,0])

print( b[:,0,0])
print (b[0])

print( b[0, :, :])

print( b[0, ...])

print (b[0,1])

print (b[0,1,::2])

print (b[...,1])

print (b[:,1])

print (b[0,:,1])

print (b[0,:,-1])
 
print (b[0,::-1, -1])


print (b[0,::2,-1])

print (b[::-1])

s = slice(None, None, -1)
print (b[(s, s, s)])

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
0
[ 0 12]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
[4 6]
[[ 1  5  9]
 [13 17 21]]
[[ 4  5  6  7]
 [16 17 18 19]]
[1 5 9]
[ 3  7 11]
[11  7  3]
[ 3 11]
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[23 22 21 20]
  [19 18 17 16]
  [15 14 13 12]]

 [[11 10  9  8]
  [ 7  6  5  4]
  [ 3  2  1  0]]]


In [33]:
#花式索引
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr


arr[[1, 5, 7, 2], [0, 3, 1, 2]]

arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [41]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr[[4, 3, 0, 6]]

arr[[-3, -5, -7]]

arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
#数组转置
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [36]:
#改变数组的维度
b = np.arange(24).reshape(2,3,4)

print( b)

print( b.ravel())

print( b.flatten())

b.shape = (6,4)

print( b)

print (b.transpose())

b.resize((2,12))

print( b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [37]:
#组合数组
a = np.arange(9).reshape(3,3)

print (a)

b = 2 * a

print (b)

print (np.hstack((a, b)))

# 水平组合
print (np.concatenate((a, b), axis=1))

print (np.vstack((a, b)))

# 垂直组合
print (np.concatenate((a, b), axis=0))

print (np.dstack((a, b)))

oned = np.arange(2)

print (oned)

twice_oned = 2 * oned

print (twice_oned)

# 列组合
print (np.column_stack((oned, twice_oned))) 

print (np.column_stack((a, b)))

print (np.column_stack((a, b)) == np.hstack((a, b)))

print (np.row_stack((oned, twice_oned)))

# 行组合
print (np.row_stack((a, b)))

print (np.row_stack((a,b)) == np.vstack((a, b)))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]
[0 1]
[0 2]
[[0 0]
 [1 2]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[[0 1]
 [0 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [43]:

#数组的分割
a = np.arange(9).reshape(3, 3)

print( a)

print (np.hsplit(a, 3))

print (np.split(a, 3, axis=1))

print (np.vsplit(a, 3))

print (np.split(a, 3, axis=0))

# 深度分割
c = (np.arange(27).reshape(3, 3, 3))

print (c)

print (np.dsplit(c, 3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]


In [45]:
import numpy as np
np.__version__

'1.14.2'