## Numpy 数据类型

      数据类型；
      数组类型；
      类型转换；
      创建数组；
      数组索引；
      数组切片；
      改变维度。
    不过，在正式学习之前，我想就本章中的示例代码做一些说明。本章代码段中的输入和输出
    均来自IPython会话。我们曾在第1章介绍过用于科学计算的交互式shell工具IPython。IPython的
    pylab模式可以自动导入包括NumPy在内的很多Python科学计算库，并且在IPython中没有必要显
    式调用 print 语句输出变量的值。不过，本书配套的源代码文件中均为使用了 import 和 print
    语句的标准Python代码。


## NumPy 数组对象
   
    NumPy中的 ndarray 是一个多维数组对象，该对象由两部分组成：
      实际的数据；
      描述这些数据的元数据。
    大部分的数组操作仅仅修改元数据部分，而不改变底层的实际数据。
    
    
    NumPy数组一般是同质的（但有一种特殊的数组类型例外，它是异质的），即数组中的所有
    元素类型必须是一致的。这样有一个好处：如果我们知道数组中的元素均为同一类型，该数组所
    需的存储空间就很容易确定下来。

In [7]:
import numpy as np
arr = np.arange(5)
print(arr)
print(arr.dtype)
arr

[0 1 2 3 4]
int32


array([0, 1, 2, 3, 4])

In [6]:
# 数组的shape属性

arr.shape
# 数组的 shape 属性
# 返回一个元组（tuple），元组中的元素即为NumPy数组每一个维度上的大小。上面例子中的数组
# 是一维的，因此元组中只有一个元素

(5,)

In [13]:
# (1) 创建一个多维数组。
# (2) 显示该数组的维度。

import numpy as np
m = np.array([np.arange(3),np.arange(3)])
print(m)
print(m.shape)

# array 函数可以依据给定的对象生成数组。给定的对象应是类数组，如Python中的列表。在
# 上面的例子中，我们传给 array 函数的对象是一个NumPy数组的列表。像这样的类数组对象是
# array 函数的唯一必要参数，其余的诸多参数均为有默认值的可选参数。

[[0 1 2]
 [0 1 2]]
(2, 3)


In [21]:
# 创建3×3的多维数组

import numpy as np

n = np.array([[np.arange(3)] * 3]*3)
print(n)
m = np.ndarray((3,3,3))
print(m)

[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
[[[ 1.13033765e-311  8.15208316e-322  0.00000000e+000]
  [ 0.00000000e+000  1.69119873e-306  1.16095484e-028]
  [-1.30976430e+179 -3.54494842e-305 -3.99868646e-020]]

 [[-2.50397927e+171  4.47433019e-067 -3.37742562e-026]
  [-4.01320607e-020 -8.60360618e+181  1.76542534e+137]
  [ 2.44001263e-152  5.98747922e+247  2.91810402e-014]]

 [[ 2.59345444e+161  9.16526748e+242  5.08972024e+222]
  [ 1.03063392e-113  7.54220740e-143  9.80058441e+252]
  [ 1.23971686e+224  9.79117529e-307  2.46155235e-312]]]


In [29]:
# 选取数组元素
# 在创建这个多维数组时，我们给 array 函数传递的对象是一个嵌套的列表。现在来依次选取
# 该数组中的元素。记住，数组的下标是从0开始的

arr = np.array([np.arange(1,3),np.arange(1,3)])
print(arr)
print(arr[0,0])
print(arr[1,1])

arr = np.array([[np.arange(3)] *3] * 3)
print(arr)
print(arr[0,0,0])



[[1 2]
 [1 2]]
1
2
[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
0
[[2.59345444e+161 9.16526748e+242 5.08972024e+222]
 [1.03063392e-113 7.54220740e-143 9.80058441e+252]
 [1.23971686e+224 9.79117529e-307 2.46155235e-312]]


In [36]:
#  用ndarray创建多维数组
m = np.ndarray((3,3,3))
print(m)
print("m[2]")
print(m[2])
print("m[1,2]")
print(m[1,2])
print("m[2,2,1]")
print(m[2,2,1])

[[[ 1.13033765e-311  8.15208316e-322  0.00000000e+000]
  [ 0.00000000e+000  1.69119873e-306  1.16095484e-028]
  [-1.30976430e+179 -3.54494842e-305 -3.99868646e-020]]

 [[-2.50397927e+171  4.47433019e-067 -3.37742562e-026]
  [-4.01320607e-020 -8.60360618e+181  1.76542534e+137]
  [ 2.44001263e-152  5.98747922e+247  2.91810402e-014]]

 [[ 2.59345444e+161  9.16526748e+242  5.08972024e+222]
  [ 1.03063392e-113  7.54220740e-143  9.80058441e+252]
  [ 1.23971686e+224  9.79117529e-307  2.46155235e-312]]]
m[2]
[[2.59345444e+161 9.16526748e+242 5.08972024e+222]
 [1.03063392e-113 7.54220740e-143 9.80058441e+252]
 [1.23971686e+224 9.79117529e-307 2.46155235e-312]]
m[1,2]
[2.44001263e-152 5.98747922e+247 2.91810402e-014]
m[2,2,1]
9.791175293693576e-307


## Numpy 的数据类型

    类 型                     描 述
    bool                      用一位存储的布尔类型（值为 TRUE 或 FALSE ）
    inti                      由所在平台决定其精度的整数（一般为 int32 或 int64 ）
    int8                      整数，范围为-128至128
    int16                     整数，范围为-32 768至32 768
    int32                     整数，范围为-2 31 至2 31 1
    int64                     整数，范围为-2 63 至2 63 1
    uint8                     无符号整数，范围为0至255
    uint16                    无符号整数，范围为0至65 535
    uint32                    无符号整数，范围为0至2 32 1
    uint64                    无符号整数，范围为0至2 64 1
    float16                   半精度浮点数（16位）：其中用1位表示正负号，5位表示指数，10位表示尾数
    float32                   单精度浮点数（32位）：其中用1位表示正负号，8位表示指数，23位表示尾数
    float64 或 float          双精度浮点数（64位）：其中用1位表示正负号，11位表示指数，52位表示尾数
    complex64                 复数，分别用两个32位浮点数表示实部和虚部
    complex128 或 complex     复数，分别用两个64位浮点数表示实部和虚部
    
    
- 每一种数据类型均有对应的类型转换函数
  
  -  需要注意的是，复数是不能转换为整数的，这将触发 TypeError 错误
   

In [91]:
import numpy as np
np.float64(42)
np.int8(-129)
np.int16(32768)

-32768

In [39]:
np.int8(42.0)

42

In [40]:
np.bool(42)

True

In [41]:
np.bool(0)

False

In [42]:
np.float(True)

1.0

In [43]:
np.float(False)

0.0

In [46]:
import numpy as np
#  在NumPy中，许多函数的参数中可以指定数据类型，通常这个参数是可选的
np.arange(7, dtype="uint16")  

# 需要注意的是，复数是不能转换为整数的，这将触发 TypeError 错误

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

## Numpy的数组对象
    
    数据类型对象是 numpy.dtype 类的实例。如前所述，NumPy数组是有数据类型的，更确切
    地说，NumPy数组中的每一个元素均为相同的数据类型。数据类型对象可以给出单个数组元素在
    内存中占用的字节数，即 dtype 类的 itemsize 属性

In [50]:
import numpy as np 
arr = np.array([np.arange(1,3),np.arange(2,4)])
print(arr)
print(arr.dtype)
print(arr.dtype.itemsize)

[[1 2]
 [2 3]]
int32
4


### NumPy可以使用字符编码来表示数据类型

    不推荐
    使用字符编码，但有时会用到，因此下面还是列出了字符编码的对应表。读者应该优先使用 dtype
    对象来表示数据类型，而不是这些字符编码
    
    数据类型      字符编码
    整数           i
    无符号整数     u
    单精度浮点数   f
    双精度浮点数   d
    布尔值         b
    复数           D
    字符串         S
    unicode字符串  U
    void （空）    V

In [54]:
import numpy as np 
arr = np.array([np.arange(2,dtype = 'f'),np.arange(3,dtype='i')])
print(arr)


[array([0., 1.], dtype=float32) array([0, 1, 2], dtype=int32)]


In [56]:
# 自定义数据类型
# 可以使用字符编码来指定单精度浮点数类型

np.dtype("f")

dtype('float32')

In [59]:
np.dtype(float)

dtype('float64')

In [62]:
# 可以使用字符编码来指定双精度浮点数类型
np.dtype("d")

dtype('float64')

In [63]:
# 还可以将两个字符作为参数传给数据类型的构造函数。此时，第一个字符表示数据类型，
# 第二个字符表示该类型在内存中占用的字节数（2、4、8分别代表精度为16、32、64位的
# 浮点数）：

np.dtype("f8")

dtype('float64')

#### dtype 类有很多有用的属性。例如，我们可以获取数据类型的字符编码



In [67]:
t = np.dtype("Float64")
print(t.char)
print(t.type)

d
<class 'numpy.float64'>


C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  """Entry point for launching an IPython kernel.


In [76]:
# 创建自定义数据类型
import numpy as np
t = np.dtype([('name', "S40"), ('numitems', "int32"), ('price',"float32")])
t

dtype([('name', 'S40'), ('numitems', '<i4'), ('price', '<f4')])

In [77]:
# 查看数据类型
import numpy as np
t = np.dtype([('name', "S40"), ('numitems', "int32"), ('price',"float32")])
t['name']

dtype('S40')

In [92]:
# 在用 array 函数创建数组时，如果没有在参数中指定数据类型，将默认为浮点数类型。而现
# 在，我们想要创建自定义数据类型的数组，就必须在参数中指定数据类型，否则将触发 TypeError
# 错误：

import numpy as np
itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], dtype=t)
itemz[1]

(b'Butter', 13, 2.72)

### 2.4 一维数组的索引和切片

- 一维数组的切片操作与Python列表的切片操作很相似

In [3]:
import numpy as np
arr = np.arange(9)
arr[2:7]

array([2, 3, 4, 5, 6])

In [4]:
# 下标0-6 步长为2
arr[:6:2]

array([0, 2, 4])

In [5]:
# 负数下标翻转数组
arr[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
# 多维数组的切片和索引

b = np.arange(24).reshape(2,3,4)
b.shape

(2, 3, 4)

In [3]:
import numpy as np
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
b.dtype

dtype('int32')

In [9]:
# 我们可以用三维坐标来选定任意一个房间，即楼层、行号和列号。例如，选定第1层楼、
# 第1行、第1列的房间（也可以说是第0层楼、第0行、第0列，这只是习惯问题），可以这样表示：

b[0,0,0]

0

In [11]:
b[:,0,0]

array([ 0, 12])

In [14]:
b[0]
b[0,:,:]
# 多个冒号可以用一个省略号代替
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
# 进而可以选取第1层楼、第2排的所有房间：

b[0,1,:]

array([4, 5, 6, 7])

In [16]:
# 再进一步，我们可以在上面的数组切片中间隔地选定元素：

b[1,2,::2]

array([20, 22])

In [18]:
# 如果要选取所有楼层的位于第2列的房间，即不指定楼层和行号，用如下代码即可：

b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [19]:
# 类似地，我们可以选取所有位于第2行的房间，而不指定楼层和列号：

b[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [20]:
# 如果要选取第1层楼的所有位于第2列的房间，在对应的两个维度上指定即可

b[0,:,1]

array([1, 5, 9])

In [22]:
# 如果要选取第1层楼的最后一列的所有房间，使用如下代码

b[0,:,-1]

array([ 3,  7, 11])

In [24]:
# 如果要反向选取第1层楼的最后一列的所有房间，使用如下代码：
(b[0,:,-1])[::-1]

array([11,  7,  3])

In [26]:
# 在该数组切片中间隔地选定元素：

b[0,::2,-1]

array([ 3, 11])

In [27]:
# 如果在多维数组中执行翻转一维数组的命令，将在最前面的维度上翻转元素的顺序，在我们
# 的例子中将把第1层楼和第2层楼的房间交换：

b[::-1,...]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

#### 动手实践：改变数组的维度



In [28]:
#  ravel 我们可以用 ravel 函数完成展平的操作

b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
#  flatten 这个函数恰如其名， flatten 就是展平的意思，与 ravel 函数的功能相同。
# 不过， flatten 函数会请求分配内存来保存结果，而 ravel 函数只是返回数组的一个视图（view）：

b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
# 用元组设置维度 除了可以使用 reshape 函数，我们也可以直接用一个正整数元组来设
# 置数组的维度

b.shape = (6,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
#  transpose 在线性代数中，转置矩阵是很常见的操作。对于多维数组，我们也可以这样做：

print(b.transpose())

[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


In [7]:
# resize resize 和 reshape 函数的功能一样，但 resize 会直接修改所操作的数组

b.resize((2,12))
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
