## 2.7 数组的组合

- NumPy数组有水平组合、垂直组合和深度组合等多种组合方式，我们将使用 vstack 、

- dstack 、 hstack 、 column_stack 、 row_stack 以及 concatenate 函数来完成数组的组合。

In [1]:
import numpy as np 
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
b = 2 * a
b 

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [3]:
# 水平组合 我们先从水平组合开始练习。将 ndarray 对象构成的元组作为参数，传给hstack 函数

np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [4]:
# 我们也可以用 concatenate 函数来实现同样的效果，如下所示：

np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [5]:
#  垂直组合  垂直组合同样需要构造一个元组作为参数，只不过这次的函数变成了vstack

np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [6]:
# 我们将 concatenate 函数的 axis 参数设置为0即可实现同样的效果。这也是 axis 参
# 数的默认值

np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [7]:
# 深度组合 将相同的元组作为参数传给 dstack 函数，即可完成数组的深度组合。所谓
# 深度组合，就是将一系列数组沿着纵轴（深度）方向进行层叠组合。举个例子，有若干张二维平
# 面内的图像点阵数据，我们可以将这些图像数据沿纵轴方向层叠在一起，这就形象地解释了什么
# 是深度组合

np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [8]:
# 列组合  column_stack 函数对于一维数组将按列方向进行组合

oned = np.arange(2)
oned

array([0, 1])

In [9]:
twice_oned = 2 * oned
twice_oned

array([0, 2])

In [10]:
np.column_stack((oned,twice_oned))


array([[0, 0],
       [1, 2]])

In [13]:
# 而对于二维数组， column_stack 与 hstack 的效果是相同的：

np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [11]:
# 行组合 当然，NumPy中也有按行方向进行组合的函数，它就是 row_stack 。对于两
# 个一维数组，将直接层叠起来组合成一个二维数组。 

np.row_stack((oned,twice_oned))

array([[0, 1],
       [0, 2]])

In [12]:
# 对于二维数组， row_stack 与 vstack 的效果是相同的

np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])



## 数组的分割

-  NumPy数组可以进行水平、垂直或深度分割，相关的函数有 hsplit 、 vsplit 、 dsplit 和

-  split 。我们可以将数组分割成相同大小的子数组，也可以指定原数组中需要分割的位置。

In [15]:
# (1) 水平分割 hsplit

import numpy as np
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [19]:
#  对同样的数组，调用 split 函数并在参数中指定参数 axis=1

np.split(a,3,axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [20]:
# (2) 垂直分割  vsplit 函数将把数组沿着垂直方向分割

np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [21]:
# 同样，调用 split 函数并在参数中指定参数 axis=0 ，也可以得到同样的结果

np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [23]:
# (3) 深度分割 不出所料， dsplit 函数将按深度方向分割数组。我们先创建一个三维数组

c = np.arange(27).reshape((3,3,3))
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
np.dsplit(c,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

### 数组的属性

In [1]:
# 除了 shape 和 dtype 属性以外， ndarray 对象还有很多其他的属性，在下面一一列出。

# ndim 属性，给出数组的维数，或数组轴的个数

import numpy as np
b = np.arange(24).reshape((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [2]:
b.ndim

2

In [3]:
# size 属性，给出数组元素的总个数，如下所示：
b.size

24

In [4]:
#itemsize 属性，给出数组中的元素在内存中所占的字节数
b.itemsize

4

In [7]:
# 如果你想知道整个数组所占的存储空间，可以用 nbytes 属性来查看。这个属性的值其实
# 就是 itemsize 和 size 属性值的乘积

print(b.nbytes)
print(b.size * b.itemsize)

96
96


In [10]:
#   T 属性的效果和 transpose 函数一样

b.resize((6,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [12]:
# 对于一维数组，其 T 属性就是原数组
b.ndim

2

In [14]:
#   在NumPy中，复数的虚部是用 j 表示的。例如，我们可以创建一个由复数构成的数组：
b = np.array([1.j + 1, 2.j + 3])
b

array([1.+1.j, 3.+2.j])

In [15]:
# real 属性，给出复数数组的实部。如果数组中只包含实数元素，则其 real 属性将输出原数组：
b.real

array([1., 3.])

In [16]:
# imag 属性，给出复数数组的虚部：
b.imag


array([1., 2.])

In [20]:
# 如果数组中包含复数元素，则其数据类型自动变为复数型：
b.dtype

dtype('complex128')

In [17]:
b.dtype.str

'<c16'

In [21]:
# flat 属性将返回一个 numpy.flatiter 对象，这是获得 flatiter 对象的唯一方式——我
# 们无法访问 flatiter 的构造函数。这个所谓的“扁平迭代器”可以让我们像遍历一维数
# 组一样去遍历任意的多维数组

import numpy as np
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [22]:
b.flat

In [23]:
for item in b.flat:
    print(item)

0
1
2
3


In [24]:
#我们还可以用 flatiter 对象直接获取一个数组元素
b.flat[2]

2

In [25]:
# flat 属性是一个可赋值的属性。对 flat 属性赋值将导致整个数组的元素都被覆盖

b.flat = 7
b

array([[7, 7],
       [7, 7]])

In [26]:
# 我们可以使用 tolist 函数将NumPy数组转换成Python列表
import numpy as np
b = np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
b.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

Hello world
