## 常用的numpy.linalg函数

           函数             说明

           diag             以一维数组的形式返回方阵的对角线(或非对角线)元素，或将一维数组转换为方阵(非对角线元素为0)

           dot              矩阵乘法

           trace            计算对角线元素的和

           det              计算矩阵行列式

           eig              计算方阵的本征值和本征向量

           inv              计算方阵的逆

           pinv             计算矩阵的Moore-Penrose伪逆

           qr               计算QR分解

           svd              计算奇异值分解(SVD)

           solve            解线性方程组Ax = b，其中A为一个方阵

           lstsq            计算Ax= b的最小二乘解

### 部分numpy.random函数

     函数          说明
     
     seed          确定随机数生成器的种子
     
     permutation   返回一个随机排列或返回一个随机排列的范围
     
     shuffle       对一个序列就地随机排列
     
     rand          产生均匀分布的样本值
     
     randint       从给定的上下范围内随机选取整数
     
     randn          产生正态分布的样本值(平均值为0，标准差为1)的样本值，类似于MATLAB接口
     
     binominal      产生二项分布的样本值
     
     normal         产生正态(高斯)分布的样本值
     
     beta           产生Beta分布的样本值

In [2]:
# 随机数生成
import numpy as np
samples = np.random.normal(size=(4,4))
samples

array([[-0.20444161, -2.10022433,  1.68130165,  0.18328666],
       [ 0.02890619,  0.09830628,  0.6273706 ,  0.78978727],
       [-1.28251844, -1.01069091,  0.87296248, -0.49634354],
       [-0.81246453, -0.21830391, -0.4035072 , -0.39149035]])

In [8]:
# 计算行列式的值

import numpy as np
np.random.seed(5)
arr = np.random.randint(-1,4,size = (3,3))
print(np.linalg.det(arr))
print(arr)

21.00000000000001
[[ 2 -1  0]
 [-1  3  2]
 [-1 -1  3]]


In [13]:
# 计算行列式的值
import numpy as np
D1 =np.array([[4,1,2,3],
              [3,4,1,2],
              [2,3,4,1],
              [1,2,3,4]])
print(np.linalg.det(D1))

160.00000000000009


In [2]:
# 矩阵的乘法
import numpy as np
x = np.array([[1,-1,3],
            [2,6,-4],
            [1,-2,-1]])
y = np.array([[-1,2,0],
            [2,-3,1],
            [-1,1,1]])
x.dot(y)

array([[ -6,   8,   2],
       [ 14, -18,   2],
       [ -4,   7,  -3]])

In [5]:
import numpy as np
np.random.seed(13)
x = np.random.randint(-2,2,size=(2,3))
y = np.random.randint(-2,2,size=(3,3))
x.dot(y)

array([[ 0, -2,  0],
       [ 4,  2,  4]])

In [15]:
import numpy as np
np.random.normal(size = (2,3))

array([[-0.8190287 ,  0.06184305,  0.707398  ],
       [ 2.27035647, -0.5448552 , -1.11904343]])

In [40]:
import numpy as np
np.random.randn(3,3)

array([[ 2.35027321, -0.91190635,  0.66579522],
       [ 0.010499  ,  0.15484641, -0.25259178],
       [-0.46035923, -0.21030488, -1.32913197]])