In [1]:
# 构建数组时 可以用dtype制定数组的类型
import numpy as np
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)



### NumPy数组基础

    数组的属性
    确定数组的大小、形状、存储大小、数据类型。
    
    数组的索引
    获取和设置数组各个元素的值。
    
    数组的切分
    在大的数组中获取或设置更小的子数组。
    
    数组的变形
    改变给定数组的形状。
    
    数组的拼接和分裂
    将多个数组合并为一个，以及将一个数组分裂成多个。

In [10]:
# numpy 数组的属性
# 用numpy的随机数组生成器生成一组种子值
import numpy as np
np.random.seed(0) # 设置随机数种子

x1 = np.random.randint(10,size=6) # 一维数组
x2 = np.random.randint(10,size=(3,4)) #二维数组
x3 = np.random.randint(10,size=(3,4,5)) #三维数组

print(x1)
print(x2)
print(x3)

# 每个数组有nidm（数组的维度）、
# shape（数组每个维度的大小）
# 和size（数组的总大小）属性
# dtype属性（数组的数据类型）
# itemsize属性(每个数组元素字节大小)
# nbytes属性 表示数组总字节大小的属性

#print("x3.nidm : ",x3.nidm)
print("x3.shape : ",x3.shape)
print("x3.size :",x3.size)
print("x3.dtype :",x3.dtype)
print("x3.itemsize:",x3.itemsize)
print("x3.nbytes:",x3.nbytes)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3.shape :  (3, 4, 5)
x3.size : 60
x3.dtype : int32
x3.itemsize: 4
x3.nbytes: 240


### 2.2.2 数组索引：获取单个元素

  - 和python列表的索引一样，numpy数组的索引也是通过中括号制定索引获取第i个值(从0开始计数)

In [11]:
x1

array([5, 0, 3, 3, 7, 9])

In [12]:
x1[0]

5

In [15]:
x1[1:-1:2]

array([0, 3])

In [17]:
x1[::-1]

array([9, 7, 3, 3, 0, 5])

In [18]:
# 在多维数组中，可以用逗号分隔的索引元组获取元素

x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [20]:
x2[0,0]

3

In [21]:
x2[2,:]

array([1, 6, 7, 7])

In [22]:
x2[:,3]

array([4, 8, 7])

In [24]:
# 也可以用索引修改元素的值

x2[0,0] = 7
x2

# 注意，和Python列表不同，NumPy数组是固定类型的。
# 这意味着当你试图将一个浮点值插入一个整型数组时，
# 浮点值会被截短成整型。并且这种截短是自动完成的，
# 不会给你提示或警告，所以需要特别注意这一点！

array([[7, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x2[2,2] = 0.1
x2

array([[7, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 0, 7]])

### 数组切片：获取子数组

    正如此前用中括号获取单个数组元素，我们也可以用切片（slice）符号获取子数组，切片符号用冒号（:）表示。NumPy切片语法和Python列表的标准切片语法相同。为了获取数组x的一个切片，可以用以下方式：
    
    x[start:stop:step]
    
    如果以上3个参数都未指定，那么它们会被分别设置默认值start=0、stop=维度的大小（size of dimension）和step=1

In [26]:
# 一维子数组
import numpy as np
np.random.seed(1)

x1 = np.random.randint(10,size = 10)
x1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [27]:
# 前五个元素
x1[:5]

array([5, 0, 3, 3, 7])

In [28]:
# 索引5之后的元素
x1[5:]

array([9, 3, 5, 2, 4])

In [29]:
# 中间的子数组
x1[4:7]

array([7, 9, 3])

In [30]:
# 每隔一个元素
x1[::2]

array([5, 3, 7, 3, 2])

In [32]:
# 逆序数组的方式

print(x1)
print(x1[::-1])

[5 0 3 3 7 9 3 5 2 4]
[4 2 5 3 9 7 3 3 0 5]


In [33]:
# 从索引5开始每隔一个元素逆序

x1[5::-2]

array([9, 3, 0])

In [34]:
# 多维子数组的切片

# 多维切片也采用同样的方式处理，用冒号分隔

import numpy as np
np.random.seed(2)
x2 = np.random.randint(10,size=(3,4))
x2

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [35]:
# 两行，三列
x2[:2,:3]

array([[5, 8, 9],
       [0, 0, 1]])

In [36]:
# 所有行，每隔一列
x2[:,::2]

array([[5, 9],
       [0, 1],
       [6, 2]])

In [38]:
# 子数组维度也可以同时被逆序
print(x2)
print(x2[::-1,::-1])

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[4 2 9 6]
 [7 1 0 0]
 [5 9 8 5]]


In [39]:
# 获取数组的行和列
# 一种常见的需求是获取数组的单行和单列。你可以将索引与切片组合起来实现这个功能，
# 用一个冒号（:）表示空切片

# 获取数组的第一列
x2[:,0] 

array([5, 0, 6])

In [41]:
# 获取数组的第三行

x2[2,:]

array([6, 9, 2, 4])

In [43]:
# 在获取行时，出于语法的简介考虑，可以省略空的切片：

x2[2]

array([6, 9, 2, 4])

In [47]:
# 4. 非副本视图的子数组
# 关于数组切片有一点很重要也非常有用，那就是数组切片返回的是数组数据的视图，
# \而不是数值数据的副本。这一点也是NumPy数组切片和Python列表切片的不同之处：
# 在Python列表中，切片是值的副本。例如此前示例中的那个二维数组：

print(x2)

x2_sub = x2[0:2,1:3]
print(x2_sub)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[8 9]
 [0 1]]


In [48]:
# 现在如果修改这个子数组，将会看到原始数组也被修改了！

x2_sub[0,0] = 1

print(x2)

# 这种默认的处理方式实际上非常有用：它意味着在处理非常大的数据集时，
# 可以获取或处理这些数据集的片段，而不用复制底层的数据缓存。

[[5 1 9 5]
 [0 0 1 7]
 [6 9 2 4]]


#### 5. 创建数组的副本
    
    尽管数组视图有一些非常好的特性，但是在有些时候明确地复制数组里的数据或子数组也是非常有用的。可以很简单地通过copy()方法实现

In [50]:
x2_sub_copy = x2[:2,1:3].copy()

print(x2_sub_copy)

x2_sub_copy[0,0] = 3

print(x2)

print(x2_sub_copy)
# 如果修改这个子数组，原始的数组不会被改变：

[[1 9]
 [0 1]]
[[5 1 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[3 9]
 [0 1]]


## 数组的变形

- 另一个有用的操作类型是数组的变形。数组变形最灵活的实现方式

- 是通过reshape()函数来实现

In [1]:
# 如果你希望将数字1~9放入一个3×3的矩阵中
import numpy as np
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
# 将一位数组转变成二维的行或列
import numpy as np
arr = np.array([1,2,3])
arr = arr.reshape((1,3))
print(arr)

[[1 2 3]]


In [5]:
# 通过newaxis获得的行向量
import numpy as np
arr[np.newaxis,:]

array([[[1, 2, 3]]])

In [6]:
# 通过变形获得的列向量

import numpy as np

arr.reshape((3,1))

array([[1],
       [2],
       [3]])

In [7]:
# 通过newaxis获得的列向量
import numpy as np
arr[:, np.newaxis]

array([[[1, 2, 3]]])

### 数组的拼接和分裂


1. 数组的拼接
   拼接或连接NumPy中的两个数组主要由np.concatenate、            np.vstack和np.hstack例程实现。
   np.concatenate将数组元组或数组列表作为第一个参数

In [8]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [10]:
# 也可一次性拼接两个以上的数组
z = np.array([7,8,9])

np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# concatenate 也可用于二维数组的拼接
# 沿一个轴拼接
import numpy as np 
a = np.arange(6).reshape((2,3))
np.concatenate([a,a])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [14]:
# 沿第二个轴拼接

import numpy as np 
a = np.arange(6).reshape((2,3))
np.concatenate([a,a],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [18]:
#沿着固定维度处理数组时，使用np.vstack（垂直栈）和np.hstack（水平栈）函数会更简洁：
import numpy as np
x = np.array([1,2,3])
y = np.arange(4,10).reshape(2,3)
np.vstack([x,y])
# 垂直栈数组

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
import numpy as np
z = np.random.randint(5,size=(2,2))
print(y)
np.hstack([y,z])
# 水平栈数组

[[4 5 6]
 [7 8 9]]


array([[4, 5, 6, 0, 4],
       [7, 8, 9, 1, 3]])




#### 数组的分裂

与拼接相反的过程是分裂。分裂可以通过np.split、np.hsplit和

np.vsplit函数来实现。可以向以上函数传递一个索引列表作为参

数，索引列表记录的是分裂点位置：

In [27]:
import numpy as np

x = np.random.randint(10,size = 8)
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

# 值得注意的是，N分裂点会得到N+1个子数组。
# 相关的np.hsplit和np.vsplit的用法也类似

[8 5 4] [0 2] [7 4 9]


In [29]:
# 垂直方向风烈
x = np.arange(16).reshape((4,4))
upper,lower = np.vsplit(x,[2])
print(upper)

print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [30]:
# 水平方向分裂
lift,right = np.hsplit(x,[2])
print(lift)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
# 同样，np.dsplit将数组沿着第三个维度分裂