In [7]:
#假定现在有关于一些人的分类数据（如姓名、年龄和体重），我们需要存储这些数据用于Python项目，那么一种可行的方法是将它们存在三个单独的数组中：
import numpy as np
name = ['Alice',"Bob","Cathy","Doug"]
age = [25,45,37,19]
weight = [55.0,85.5,68.0,61.5]
x = np.zeros(4,dtype=int)
print(x)
# # 使用复合数据结构的结构化数组
data = np.zeros(4,dtype={"names":("name","age","weight"),
                     "formats":("U10","i4","f8")})
print(data.dtype)

[0 0 0 0]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [12]:
data["name"] = name
data['age'] = age
data["weight"] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [13]:
data["name"]

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [14]:
# 获取第一行
data[0]

('Alice', 25, 55.)

In [15]:
data[-1]["name"]

'Doug'

In [16]:
# 获取年龄小于30岁人的名字
data[data["age"]<30]["name"]

array(['Alice', 'Doug'], dtype='<U10')

### 生成结构化数组

- 上面为经典的字典结构化数组的方法

![Numpy的数组类型](./media/Numpy的数据类型.PNG)

In [17]:
import numpy as np
np.dtype({"names":("name","age","weight"),
         "formats":('U10',"i4","f8")})
# 为了简明起见，数值数据类型可以用Python类型或NumPy的dtype类型指定

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [18]:
np.dtype({"names":("name","age","weight"),
         "formats":((np.str_,10),int,np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [19]:
# 更高级的数的数据类型
import numpy as np
tp = np.dtype([('id',"i8"),("mat","f8",(3,3))])
X = np.zeros(1,dtype=tp)
print(X[0])
print(X["mat"][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 记录数组：结构化数组的扭转

    NumPy还提供了np.recarray类。它和前面介绍的结构化数组几乎相同，但是它有一个独特的特征：域可以像属性一样获取，而不是像字典的键那样获取。前面的例子通过以下代码获取年龄：

In [20]:
data["age"]

array([25, 45, 37, 19])

In [22]:
# 如果将这些数据当作一个记录数组，我们可以用很少的按键来获取这个结果：
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])