In [1]:
import numpy as np

In [8]:
# 生成10名同学，5门功课的数据
score = np.random.randint(0,100,(10,5))

# 逻辑运算

In [9]:
# 取出最后4名同学的成绩，用于逻辑判断
temp = score[6:,:]

In [10]:
temp>60

array([[ True, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True,  True,  True,  True],
       [False, False,  True, False, False]])

In [7]:
temp 

array([[99, 87, 74, 83, 80],
       [62, 91, 74, 98, 88],
       [66, 71, 94, 77, 69],
       [71, 67, 70, 69, 99]])

In [11]:
temp[temp>60] = 1

In [12]:
temp

array([[ 1, 10,  4, 53,  0],
       [12, 24,  1, 27, 36],
       [16,  1,  1,  1,  1],
       [14, 60,  1,  2, 31]])

In [14]:
#判断前两名同学的成绩[0:2, :]是否全及格
np.all(score[:2,:]>60)

False

In [19]:
# 判断前两名同学的成绩[0:2, :]是否有大于90分的
np.any(score[:2,:]>=90)

True

In [18]:
score[:2,:]

array([[51, 71, 49, 82,  7],
       [29, 16, 20,  7, 90]])

# 三元运算

In [20]:
np.where(1>0,1,0)

array(1)

In [22]:
# 判断前四名学生,前四门课程中，成绩中大于60的置为1，否则为0
score[:4,:4]

array([[51, 71, 49, 82],
       [29, 16, 20,  7],
       [38, 27, 73, 83],
       [16,  8, 86, 95]])

In [23]:
np.where(score[:4,:4]>60,1,0)

array([[0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1]])

In [27]:
# 判断前四名学生,前四门课程中，成绩中大于60且小于90的换为1，否则为0
np.where(np.logical_and(score[:4,:4]>60,score[:4,:4]<90),1,0)

array([[0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 0]])

In [26]:
score[:4,:4]

array([[51, 71, 49, 82],
       [29, 16, 20,  7],
       [38, 27, 73, 83],
       [16,  8, 86, 95]])

In [30]:
# # 判断前四名学生,前四门课程中，成绩中大于90或小于60的换为1，否则为0
np.where(np.logical_or(score[:4,:4]>90,score[:4,:4]<60),1,0)

array([[1, 0, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1]])

# 统计函数

In [36]:
# 前四名学生,各科成绩的最大分
print("前四名学生,各科成绩的最大分{}".format(np.max(score[:4,:],axis=0)))

前四名学生,各科成绩的最大分[51 71 86 95 90]


In [37]:
# 前四名学生,各科成绩的最大分
print("前四名学生,各科成绩的最小分{}".format(np.min(score[:4,:],axis=0)))

前四名学生,各科成绩的最小分[16  8 20  7  5]


In [38]:
print("前四名学生,各科成绩的波动情况{}".format(np.std(score[:4,:],axis=0)))

前四名学生,各科成绩的波动情况[12.77693234 24.33618705 25.14955268 34.87387991 34.30287889]


In [39]:
# 前四名学生，各科成绩最高分对应的学生下标：
print("前四名学生,各科成绩的最大分的下标{}".format(np.argmax(score[:4,:],axis=0)))

前四名学生,各科成绩的最大分的下标[0 0 3 3 1]


In [40]:
score[:4,:]

array([[51, 71, 49, 82,  7],
       [29, 16, 20,  7, 90],
       [38, 27, 73, 83, 33],
       [16,  8, 86, 95,  5]])

In [41]:
print("前四名学生,各科成绩的最小分的下标{}".format(np.argmin(score[:4,:],axis=0)))

前四名学生,各科成绩的最小分的下标[3 3 1 1 3]


# 数组运算

## 数组与数的运算

In [42]:
arr = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])

In [43]:
arr

array([[1, 2, 3, 2, 1, 4],
       [5, 6, 1, 2, 3, 1]])

In [44]:
arr+1

array([[2, 3, 4, 3, 2, 5],
       [6, 7, 2, 3, 4, 2]])

In [45]:
arr/2

array([[0.5, 1. , 1.5, 1. , 0.5, 2. ],
       [2.5, 3. , 0.5, 1. , 1.5, 0.5]])

##  数组与数组的运算

In [47]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [48]:
arr1

array([[1, 2, 3, 2, 1, 4],
       [5, 6, 1, 2, 3, 1]])

In [49]:
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [51]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (2,6) (2,4) 

In [52]:
arr1+arr1

array([[ 2,  4,  6,  4,  2,  8],
       [10, 12,  2,  4,  6,  2]])

In [53]:
arr1 = np.array([[0],[1],[2],[3]])

In [54]:
arr1

array([[0],
       [1],
       [2],
       [3]])

In [55]:
arr2 = np.array([1,2,3])

In [56]:
arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [57]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [58]:
arr1

array([[1, 2, 3, 2, 1, 4],
       [5, 6, 1, 2, 3, 1]])

In [59]:
arr2

array([[1],
       [3]])

In [60]:
arr1+arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

# 矩阵运算

In [61]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])
b = np.array([[0.7], [0.3]])

In [62]:
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [63]:
np.matmul(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [64]:
np.matmul(a,2)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [65]:
np.dot(a,2)

array([[160, 172],
       [164, 160],
       [170, 156],
       [180, 180],
       [172, 164],
       [164, 180],
       [156, 160],
       [184, 188]])