In [1]:
# 二维数组的切片
import numpy as np
np.random.seed(0)
arr = np.random.randint(0,10,size=(2,3))

In [2]:
arr

array([[5, 0, 3],
       [3, 7, 9]])

In [3]:
arr[1,1]

7

In [5]:
arr[:,1]

array([0, 7])

In [6]:
# 默认取的为行
arr[1]

array([3, 7, 9])

In [7]:
# 三维数组的切片
arr1 = np.random.randint(0,10,size=(3,3,4))

In [8]:
arr1

array([[[3, 5, 2, 4],
        [7, 6, 8, 8],
        [1, 6, 7, 7]],

       [[8, 1, 5, 9],
        [8, 9, 4, 3],
        [0, 3, 5, 0]],

       [[2, 3, 8, 1],
        [3, 3, 3, 7],
        [0, 1, 9, 9]]])

In [9]:
# 每个逗号表示一维数据
arr1[1,1,2]

4

In [10]:
# 取出列
arr1[2,:,2]

array([8, 3, 9])

In [11]:
# 形状的修改
arr1.shape

(3, 3, 4)

In [13]:
arr1

array([[[3, 5, 2, 4],
        [7, 6, 8, 8],
        [1, 6, 7, 7]],

       [[8, 1, 5, 9],
        [8, 9, 4, 3],
        [0, 3, 5, 0]],

       [[2, 3, 8, 1],
        [3, 3, 3, 7],
        [0, 1, 9, 9]]])

In [22]:
arr2 = np.arange(0,20).reshape(4,5)

In [23]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
arr2.shape

(4, 5)

In [25]:
# reshape不会改变原来的数据
arr2.reshape((-1,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [26]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
# resize
arr2.resize((2,10))

In [29]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [30]:
arr2 = np.arange(0,20).reshape(4,5)

In [31]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
# 数组的转置
arr2.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
# 类型的修改
ndarray.astype(type)

In [33]:
arr2.astype(np.float32)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)

In [34]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
arr2.tostring()

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00'

In [41]:
# 数组的去重
arr3 = np.random.randint(0,5,size=(3,4))

In [42]:
arr3

array([[1, 4, 1, 2],
       [2, 0, 1, 1],
       [1, 1, 3, 3]])

In [43]:
tem = np.unique(arr3)

In [44]:
tem

array([0, 1, 2, 3, 4])

创建数组【掌握】

生成0和1的数组
np.ones()
np.ones_like()
从现有数组中生成
np.array -- 深拷贝
np.asarray -- 浅拷贝
生成固定范围数组

np.linspace()
nun -- 生成等间隔的多少个
np.arange()
step -- 每间隔多少生成数据
np.logspace()
生成以10的N次幂的数据
生层随机数组

正态分布
里面需要关注的参数:均值:u, 标准差:σ
u -- 决定了这个图形的左右位置
σ -- 决定了这个图形是瘦高还是矮胖
np.random.randn()
np.random.normal(0, 1, 100)
均匀
np.random.rand()
np.random.uniform(0, 1, 100)
np.random.randint(0, 10, 10)
数组索引【知道】

直接进行索引,切片
对象[:, :] -- 先行后列
数组形状改变【掌握】

对象.reshape()
没有进行行列互换,新产生一个ndarray
对象.resize()
没有进行行列互换,修改原来的ndarray
对象.T
进行了行列互换
数组去重【知道】

np.unique(对象)