In [13]:
import numpy as np
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [14]:
import numpy as np
np.random.randint(0,100,size=(10,5))

array([[25, 21, 86, 98, 75],
       [33, 11, 89, 12, 52],
       [33, 63, 24, 12, 81],
       [26,  3, 54, 41, 38],
       [40, 83, 75, 29, 64],
       [ 7, 96, 92, 70, 77],
       [57, 25, 99,  1, 79],
       [16, 80, 35, 87, 39],
       [16, 99, 86, 14, 20],
       [48, 77, 31, 42, 37]])

In [23]:
import random
import time
a = []
for i in range(10000000):
    a.append(random.random())
print("原生python计算用时为")
%time sum(a)
print("numpy计算用时为")
b = np.array(a)
%time np.sum(b)

原生python计算用时为
Wall time: 92 ms
numpy计算用时为
Wall time: 32 ms


4999572.467591602

In [24]:
arr = np.arange(12).reshape(3,4)

In [25]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
# 数组维数
arr.ndim

2

In [31]:
# 数组维度的元组
arr.shape

(3, 4)

In [27]:
# 数组中元素的个数
arr.size

12

In [28]:
# 一个数组中元素的长度
arr.itemsize

4

In [30]:
# 数组的数据类型
arr.dtype

dtype('int32')

In [32]:
# 二维数组
np.random.randint(0,10,size=(2,3))

array([[2, 7, 8],
       [5, 9, 9]])

In [33]:
# 三维数组,最外面为三个，每个数组有4行，2列
np.random.randint(0,10,size=(3,4,2))

array([[[8, 2],
        [5, 5],
        [8, 8],
        [9, 6]],

       [[4, 9],
        [0, 9],
        [3, 7],
        [8, 6]],

       [[5, 7],
        [9, 2],
        [2, 1],
        [9, 5]]])

In [38]:
# 设置数组的数据类型
arr = np.random.randint(60,100,size=(3,4))

array([[78, 78, 81, 93],
       [64, 68, 95, 83],
       [63, 65, 76, 85]])

In [43]:
arr.dtype=np.float16

In [44]:
arr

array([[0.0e+00, 0.0e+00, 6.0e-08, 0.0e+00, 1.2e-07, 0.0e+00, 1.8e-07,
        0.0e+00],
       [2.4e-07, 0.0e+00, 3.0e-07, 0.0e+00, 3.6e-07, 0.0e+00, 4.2e-07,
        0.0e+00],
       [4.8e-07, 0.0e+00, 5.4e-07, 0.0e+00, 6.0e-07, 0.0e+00, 6.6e-07,
        0.0e+00]], dtype=float16)

In [45]:
# 创建数组的时候指定索索引
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)

In [46]:
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [48]:
# 生成0 1 数组
import numpy as np
arr = np.zeros((2,3,4))

In [49]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [52]:
arr.dtype

dtype('float64')

In [53]:
arr = np.ones((3,3,3),dtype='int64')

In [54]:
arr

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int64)

In [55]:
# 生成结构一样的数表
np.zeros_like(arr)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

### 从现有数组生成

In [68]:
a = np.arange(8).reshape(4,2)

In [57]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [75]:
a[0,0] = 100

In [71]:
# 从现有数组中创建，深拷贝
a1 = np.array(a)

In [76]:
a1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [73]:
# 如果a数组发生变化，则a1也会变化 ，浅拷贝，相当于快捷方式
a2 = np.asarray(a)

In [77]:
a2

array([[100,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7]])