In [1]:
#逻辑运算
import numpy as np
np.random.seed(1)

In [2]:
# 生成10名同学，五门功课的数据
score = np.random.randint(0,100,size=(10,5))

In [3]:
score

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87],
       [87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22],
       [57,  1,  0, 60, 81],
       [ 8, 88, 13, 47, 72],
       [30, 71,  3, 70, 21]])

In [4]:
# 取出最后四名同学的成绩
test_score = score[-4:,:]

In [5]:
test_score

array([[ 9,  7, 63, 61, 22],
       [57,  1,  0, 60, 81],
       [ 8, 88, 13, 47, 72],
       [30, 71,  3, 70, 21]])

In [6]:
# 进行逻辑运算
test_score > 60

array([[False, False,  True,  True, False],
       [False, False, False, False,  True],
       [False,  True, False, False,  True],
       [False,  True, False,  True, False]])

In [9]:
test_score[test_score >= 60] = 1

In [10]:
test_score

array([[ 9,  7,  1,  1, 22],
       [57,  1,  0,  1,  1],
       [ 8,  1, 13, 47,  1],
       [30,  1,  3,  1, 21]])

In [ ]:
# 通用判断函数

In [19]:
# 判断前两名的成绩是否全部合格
np.all(score[:2,:] > 60)

False

In [20]:
# 判断前两名的成绩是否有大于90的
np.any(score[:2,:] >90)

False

In [ ]:
# np.where（条件，判断为真执行的代码。判断为假执行的代码） 三元运算符
# 复合逻辑需要结合np.logical_and和np.logical_or使用

In [18]:
# 判断前四名学生,前四门课程中，成绩中大于60且小于90的换为1，否则为0
np.where(np.logical_and(score[:4,:4] >60,score[:4,:4] < 90),1,0)

array([[0, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0]])

In [21]:
# 判断前四名学生,前四门课程中，成绩中大于90或小于60的换为1，否则为0
np.where(np.logical_or(score[:4,:4] >90,score[:4,:4] < 60),1,0)

array([[1, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 1, 1],
       [1, 1, 0, 1]])

In [ ]:
# 统计计算
# 4.1 统计指标
# 在数据挖掘/机器学习领域，统计指标的值也是我们分析问题的一种方式。常用的指标如下：

# min(a, axis)
# Return the minimum of an array or minimum along an axis.
# max(a, axis])
# Return the maximum of an array or maximum along an axis.
# median(a, axis)
# Compute the median along the specified axis.
# mean(a, axis, dtype)
# Compute the arithmetic mean along the specified axis.
# std(a, axis, dtype)
# Compute the standard deviation along the specified axis.
# var(a, axis, dtype)
# Compute the variance along the specified axis.

In [22]:
# 学生成绩统计计算
# 对前四名学生，进行一些统计计算
tem = score[:4,:]

In [24]:
tem

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28]])

In [25]:
# 前四名学生，各科成绩的最大分
np.max(tem,axis=0)

array([76, 79, 84, 25, 75])

In [26]:
# 前四名学生，各科成绩的最小分
np.min(tem,axis=0)

array([ 5, 12,  6,  9,  1])

In [27]:
# 前四名学生，各科成绩的波动情况
np.std(tem,axis=0)

array([26.5       , 30.20761493, 30.0124974 ,  6.17960355, 27.29926739])

In [28]:
# 前四名学生，各科成绩的平均分
np.mean(tem,axis=0)

array([34.5 , 45.  , 56.5 , 15.25, 38.5 ])

In [ ]:
# 统计出某科最高分对应的同学
# np.argmax(temp, axis=)
# np.argmin(temp, axis=)

In [30]:
np.argmax(tem,axis=1)

array([4, 1, 0, 2], dtype=int64)

## 5 小结
- 
```
    逻辑运算【知道】
    直接进行大于,小于的判断
    合适之后,可以直接进行赋值
    通用判断函数【知道】
    np.all()
    np.any()
    统计运算【掌握】
    np.max()
    np.min()
    np.median()
    np.mean()
    np.std()
    np.var()
    np.argmax(axis=) — 最大元素对应的下标
    np.argmin(axis=) — 最小元素对应的下标
    ```