# 数组与数的运算

In [33]:
import numpy as np
np.random.seed(1)
arr = np.random.randint(0,100,size=(3,4))

In [4]:
arr

array([[37, 12, 72,  9],
       [75,  5, 79, 64],
       [16,  1, 76, 71]])

In [5]:
# 数组中每个元素加1
arr + 1

array([[38, 13, 73, 10],
       [76,  6, 80, 65],
       [17,  2, 77, 72]])

In [6]:
arr * 3

array([[111,  36, 216,  27],
       [225,  15, 237, 192],
       [ 48,   3, 228, 213]])

In [11]:
# 数组与数组的运算，广播机制
# A  (1d array): 10
# B  (1d array): 12
# A  (2d array):      2 x 1
# B  (3d array):  8 x 4 x 3
arr1 = np.random.randint(0,10,size=(3,4))

In [12]:
arr1

array([[4, 0, 3, 9],
       [2, 0, 4, 9],
       [2, 7, 7, 9]])

In [22]:
arr2 = np.random.randint(0,10,size=(1,4))

In [23]:
arr2

array([[8, 4, 4, 7]])

In [24]:
arr1 + arr2

array([[12,  4,  7, 16],
       [10,  4,  8, 16],
       [10, 11, 11, 16]])

In [25]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [26]:
arr1 + arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

In [ ]:
# 矩阵必须是二维的，但array可以是多维的

In [53]:
np.random.seed(2)
m = np.random.randint(0,10,size=(3,2))

In [54]:
m

array([[8, 8],
       [6, 2],
       [8, 7]])

In [49]:
np.random.seed(1)
n = np.random.randint(0,10,size=(3,2))

In [50]:
n

array([[5, 8],
       [9, 5],
       [0, 0]])

In [55]:
m + n

array([[13, 16],
       [15,  7],
       [ 8,  7]])

In [56]:
m + 1

array([[9, 9],
       [7, 3],
       [9, 8]])

In [57]:
m * 2

array([[16, 16],
       [12,  4],
       [16, 14]])

In [60]:
np.random.seed(1)
n = np.random.randint(0,10,size=(2,3))

In [61]:
# 矩阵的向量乘法
# np.matmul和np.dot的区别:

# 二者都是矩阵乘法。 np.matmul中禁止矩阵与标量的乘法。 在矢量乘矢量的內积运算中，np.matmul与np.dot没有区别。
# np.dot(m,n)

array([[80, 64, 72],
       [40, 48, 54],
       [75, 64, 72]])