课程介绍

1. 逻辑回归

   分类

2. 决策树

   分类

# 3.1 逻辑回归介绍

分类

逻辑回归（Logistic Regression）是机器学习中的**一种分类模型**

## 1 逻辑回归的应用场景

- 广告点击率     
- 是否为垃圾邮件    目标  是 否
- 是否患病   目标  是 否 
- 金融诈骗
- 虚假账号

分类,  二个  解决二分类问题的利器

是=1   正例

否=0  负例

## 2 逻辑回归的原理

线性回归输出是我们逻辑回归输入

### 2.2 激活函数

sigmoid函数

逻辑回归结果  [0,1]

二分类   大于阈值  ==>正例

​				小于阈值 ==>负例

阈值:  0.5(正常)  不一定 

阈值?

## 3 损失以及优化

逻辑回归的损失，称之为**对数似然损失**

优化目标

当y=1  **hθ(x)** 越大越好

当y=0 hθ(x)** 越小越好

### 3.2 优化

**提升原本属于1类别的概率，降低原本是0类别的概率。**

# 3.2 逻辑回归api介绍

sklearn.linear_model.LogisticRegression(solver='liblinear', penalty=‘l2’, C = 1.0)

- 对于小数据集来说，“liblinear”是个不错的选择，而“sag”和'saga'对于大型数据集会更快。
- 对于多类问题，只有'newton-cg'， 'sag'， 'saga'和'lbfgs'可以处理多项损失;“liblinear”仅限于“one-versus-rest”分类。

- penalty：正则化的种类

- C：正则化力度

- 

- # 3.3 案例：癌症分类预测-良／恶性乳腺癌肿瘤预测

目标: 良性和恶性   二分类   ---逻辑回归

建模流程

1. 获取数据

2. 数据基本处理

   2.1 缺失值处理

   2.2 确定特征值和目标值

   2.3 切割数据

3. 特征工程

   特征标准化

4. 建立模型

   逻辑回归

5. 模型评估

# 3.4 分类评估方法

 混淆矩阵

ROC AUC

## 1.分类评估方法

### 1.1 精确率与召回率

#### 1.1.1 混淆矩阵

准度度: (TP+TN)/(TP+TN +FN+FP)

#### 精确率(Precision)

TP/(TP+FP)   查的准

召回率

TP/(TP+FN)  查的全

### 1.2 F1-score

反映模型的稳健性

值越大越好

### 1.3 分类评估报告api

- sklearn.metrics.classification_report(y_true, y_pred, labels=[], target_names=None )
- - y_true：真实目标值
  - y_pred：估计器预测目标值
  - labels:指定类别对应的数字
  - target_names：目标类别名称
  - return：每个类别精确率与召回率

## 2 ROC曲线与AUC指标

选择不同的阈值计算Fpr和TPR值落在二维平面上 

寻找最优阈值

AUC指标 ROC曲线线下面积

取值[0,1]一般[0.5,1]

### 2.3 AUC指标

取一对正负样本，正样本得分大于负样本得分的概率 (越大越好)

AUC的范围在[0, 1]之间，并且越接近1越好，越接近0.5属于乱猜

**AUC=1，完美分类器**

**0.5<AUC<1，优于随机猜测。这个分类器（模型）妥善设定阈值的话，能有预测价值。**

### 2.4 AUC计算API

from sklearn.metrics import roc_auc_score

- sklearn.metrics.roc_auc_score(y_true, y_score)

  - 计算ROC曲线面积，即AUC值
  - y_true：每个样本的真实类别，必须为0(反例),1(正例)标记
  - y_score：预测得分，可以是正类的估计概率、置信值或者分类器方法的返回值

  适合样本不均衡问题

  # 3.5 ROC曲线的绘制

  1. 计算逻辑回归结果
  2. 逻辑回归结果从大到小
  3. 设定不同阈值计算FPR和TPR
  4. 将FPR和TPR落在二维平面上 

  ROC靠近左上角 的阈值 就是最优阈值

  适合不均衡样本

  # 决策树算法

  什么是决策树

  1. 是一个树形结构
  2. 每个非叶子节点代表的是一个判断
  3. 叶子节点代表的是一个分类结果

  if -else

如何构建决策树

​	1 . 特征重要性前后

2. 切割点

# 4.2 决策树分类原理

如何构树 

  1 . 特征重要性前后

2. 切割点

## 1 熵(**信息熵**)

物理学上，**熵 Entropy** 是“混乱”程度的量度。

数据有序,熵小

数据混乱 熵大

构树:  让熵变小的过程

![image-20191116111413485](/Users/zhangqingtao/Library/Application Support/typora-user-images/image-20191116111413485.png)



## 2 决策树的划分依据

1. ID3--信息增益
2. C4.5 -信息增益率
3. CART-基尼指数

### 信息增益(ID3)(熵)

**信息增益 = entroy(前) - entroy(后)**

根据条件划分决策树 熵值差

信息增益越大越好

![image-20191116113557970](/Users/zhangqingtao/Library/Application Support/typora-user-images/image-20191116113557970.png)

**信息增益(a="性别")**

0.0064

**信息增益(a="活跃度")**

0.6776

选择信息增益大的作为第一决策依据

**活跃度**

信息增益 :选择类别多的属性作为第一决策依据

### 信息增益率(C4.5)(熵)

对信息增益的改进

改进:对类别多的属性有所偏好

![image-20191116120747824](/Users/zhangqingtao/Library/Application Support/typora-user-images/image-20191116120747824.png)

选择信息增益率大作为第一决策依据

while(当前节点"不纯")---(熵不为0 )

​	1 .  计算熵值

	2. 计算条件熵
 	3. 计算信息增益
 	4. 计算信息增益率
 	5. 选择增益率大的作为第一属性

### 3.3 为什么使用C4.5要好

**1.用信息增益率来选择属性**

克服信息增益选择类别多的属性作为第一决策依据

**2.采用了一种后剪枝方法**

从低向上如果减枝效果比不减好--执行减

**3.对于缺失值的处理**

C4.5比ID3 要好

### 基尼值和基尼指数(CART)

二叉树

**基尼值Gini（D）**

越小越好

数据的纯度:  值越小纯度越高

![image-20191116144351396](/Users/zhangqingtao/Library/Application Support/typora-user-images/image-20191116144351396.png)

**基尼指数Gini_index（D）**

![image-20191116144512545](/Users/zhangqingtao/Library/Application Support/typora-user-images/image-20191116144512545.png)

现在我们来总结一下CART的算法流程

1. ```
   while(当前节点不纯) ---基尼值不为0
   1.遍历每个变量的每一种分割方式，找到最好的分割点----基尼指数值小
   2.分割成两个节点N1和N2
   每个节点足够“纯”为止
   ```

### 5.1 常见决策树的启发函数比较

#### **5.1.1 ID3 算法**

**存在的缺点**

1. 选择类别多的属性作为第一决策依据
2. 只能构建离散型(男,女....类别型)特征构建树

#### **5.1.2 C4.5算法**

(1) 用信息增益率来选择属性

 (2) 可以处理连续数值型属性(年收入)

(3)采用了一种后剪枝方法

(4)对于缺失值的处理

**C4.5算法的优缺点**

优点:

 易于理解，准确率较高。

缺点: 

算法低效

C4.5只适合于能够驻留于内存的数据集(后减枝)

#### 5.1.3 CART算法

二叉树

处理离散型.连续型特征

**C4.5不一定是二叉树，但CART一定是二叉树**

#### 5.1.4 多变量决策树(multi-variate decision tree)

**分类决策不应该是由某一个特征决定的，而是应该由一组特征决定的。**

### 5.2 决策树变量的两种类型：

1. 数字型  连续型 年收入
2. 名称型  离散型 类别型  婚姻状况

### **5.3 如何评估分割点的好坏？**

找到能让数据最快达到"纯"的分割点就是好

# 4.3 cart剪枝

## 1 为什么要剪枝

随着判断节点的增加 训练集效果越好越好

​									测试集效果 先上升后下降

存在过拟合现象

**出现这种情况的原因**

原因1：噪声、样本冲突，即错误的样本数据。

原因2：特征即属性不能完全作为分类标准。

原因3：巧合的规律性，数据量不够大。

## 2 常用的减枝方法

1. 预减枝

   1. 指定每一个结点所包含的最小样本数目，
   2. 指定高度或深度
   3. 指定一个阈值 ,熵小于阈值 就不往下划分

2. 后减枝

   后剪枝，在已生成过拟合决策树上进行剪枝，可以得到简化版的剪枝决策树。

工作:后减枝

# 4.4 特征工程-特征提取

1. 特征提取
2. 特征预处理(标准化)
3. 特征降维

## 1 特征提取

**将任意数据（如文本或图像）转换为可用于机器学习的数字特征**

分类

1. 字典特征提取(特征离散化)
2. 文本特征提取
3. 图像特征提取

### 1.2 特征提取API

```python
sklearn.feature_extraction
```



## 2 字典特征提取

sklearn.feature_extraction.DictVectorizer(sparse=True,…)

- DictVectorizer.fit_transform(X)
  - X:字典或者包含字典的迭代器返回值
  - 返回sparse矩阵
- DictVectorizer.get_feature_names() 返回类别名称

transfer = DictVectorizer()

transfer.fit_transform(x)

**sparse 矩阵** 非0 的位置和值

稀疏矩阵- 适合用sparse 

## 3 文本特征提取

### 英文文本提取

**sklearn.feature_extraction.text.CountVectorizer(stop_words=[])**

统计频次 like  2

stop_words: 停用词[is,]

### 3.3 jieba分词处理

import jieba

jieba.cut()





### 决策树：
- 是一种树形结构，其中每个内部节点表示一个属性上的判断，每个分支代表一个判断结果的输出，最后每个叶节点代表一种分类结果，本质是一颗由多个判断节点组成的树。

- 系统越有序，熵值越低；系统越混乱或者分散，熵值越高。

- 信息增益：以某特征划分数据集前后的熵的差值。熵可以表示样本集合的不确定性，熵越大，样本的不确定性就越大。因此可以使用划分前后集合熵的差值来衡量使用当前特征对于样本集合D划分效果的好坏。

- 信息增益 = entroy(前) - entroy(后)

In [12]:
# 计算类别信息熵
import numpy as np
ent_d = -5/15*np.log2(5/15)-10/15*np.log2(10/15)
ent_d

0.9182958340544896

In [9]:
# 计算性别属性的信息熵
a = -3/8*(np.log2(3/8)) - 5/8*(np.log2(5/8))
a

0.954434002924965

In [11]:
b = -2/7*np.log2(2/7)-5/7*np.log2(5/7)
b

0.863120568566631

In [28]:
# 计算性别的信息增益
gain1 = ent_d - 8/15*a-7/15*b
gain1

0.006474767163413719

In [16]:
# 计算活跃度属性信息熵
high = -0/6*np.log2(0/6) - 6/6*np.log2(6/6)
high = 0

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log2
  
C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in double_scalars
  


nan

In [23]:
mid = -1/5*np.log2(1/5)-4/5*np.log2(4/5)
mid

0.7219280948873623

In [29]:
# 计算活跃度信息增益
gain2 = ent_d - 5/15*mid
gain2

0.6776531357587021

- 活跃度的信息增益比性别的信息增益大，也就是说，活跃度对用户流失的影响比性别大。在做特征选择或者数据分析的时候，我们应该重点考察活跃度这个指标。

## 3 决策树的划分依据二----信息增益率
- 增益率：增益率是用前面的信息增益Gain(D, a)和属性a对应的"固有值"(intrinsic value) [Quinlan , 1993J的比值来共同定义的。

```

3.2.1 案例一
a.计算类别信息熵

b.计算性别属性的信息熵(性别、活跃度)

c.计算活跃度的信息增益(性别、活跃度)

d.计算属性分裂信息度量
```

In [31]:
# 计算类别信息熵
# x性别
iv1 = -8/15*np.log2(8/15)-7/15*np.log2(7/15)
iv1

0.9967916319816366

In [27]:
# 活跃度
iv2 = -6/15*np.log2(6/15)-5/15*np.log2(5/15)-4/15*np.log2(4/15)
iv2

1.5655962303576019

In [32]:
# 计算信息增益率
gain_ratio1 = gain1/iv1
gain_ratio1

0.00649560746265675

In [33]:
gain_ratio2 = gain2/iv2
gain_ratio2

0.43284029599631674

### 3.2.2 案例二
- 如下图，第一列为天气，第二列为温度，第三列为湿度，第四列为风速，最后一列该活动是否进行。

In [10]:
import numpy as np
# 计算类别的信息熵
ent = -9/14*np.log2(9/14)-5/14*np.log2(5/14)
ent

0.9402859586706311

In [12]:
# 计算每个属性的信息熵
# 天气
ent_tq = 5/14*(-2/5*np.log2(2/5)-3/5*np.log2(3/5)) + 5/14*(-3/5*np.log2(3/5)-2/5*np.log2(2/5))
ent_tq

0.6935361388961918

In [16]:
# 温度
ent_wd = 4/14 *(-2/4*np.log2(2/4)-2/4*np.log2(2/4))+ \
6/14*(-4/6*np.log2(4/6)-2/6*np.log2(2/6))+ \
4/14*(-3/4*np.log2(3/4)-1/4*np.log2(1/4))
ent_wd

0.9110633930116763

In [18]:
# 湿度
ent_sd = 7/14*(-3/7*np.log2(3/7)-4/7*np.log2(4/7))+ \
7/14*(-6/7*np.log2(6/7)-1/7*np.log2(1/7))
ent_sd

0.7884504573082896

In [20]:
# 风速
ent_fs = 9/14*(-7/9*np.log2(7/9)-2/9*np.log2(2/9))+\
5/14*(-2/5*np.log2(2/5)-3/5*np.log2(3/5))
ent_fs

0.8380423950607804

In [22]:
# 计算每个属性的信息增益
gain_tq = ent-ent_tq
gain_tq

0.24674981977443933

In [23]:
gain_wd = ent-ent_wd
gain_wd

0.02922256565895487

In [24]:
gain_sd = ent-ent_sd
gain_sd

0.15183550136234159

In [25]:
gain_fs = ent-ent_fs
gain_fs

0.10224356360985076

In [26]:
# 计算属性分裂信息度量
iv_tq = -5/14*np.log2(5/14)-4/15*np.log2(4/15)-5/14*np.log2(5/14)
iv_tq

1.569523321093397

In [27]:
iv_wd = -4/14*np.log2(4/14)-6/14*np.log2(6/14)-4/14*np.log2(4/14)
iv_wd

1.5566567074628228

In [29]:
iv_sd = -7/14*np.log2(7/14)-7/14*np.log2(7/14)
iv_sd

1.0

In [30]:
iv_fs = -9/14*np.log2(9/14)-5/14*np.log2(5/14)
iv_fs

0.9402859586706311

In [31]:
# 计算信息 增益率
gain_r_tq = gain_tq/iv_tq
gain_r_tq

0.15721322293098702

In [32]:
gain_r_wd = gain_wd/iv_wd
gain_r_wd

0.018772646222418813

In [33]:
gain_r_sd = gain_sd/iv_sd
gain_r_sd

0.15183550136234159

In [34]:
gain_r_fs = gain_fs/iv_fs
gain_r_fs

0.1087366695918781

```
while(当前节点"不纯")：
    1.计算当前节点的类别熵(以类别取值计算)
    2.计算当前阶段的属性熵(按照属性取值吓得类别取值计算)
    3.计算信息增益
    4.计算各个属性的分裂信息度量
    5.计算各个属性的信息增益率
end while
当前阶段设置为叶子节点
```

In [44]:
# 决策树的划分依据三 基尼值和基尼指数
x = 1/6*0+5/6*(1-(3/5)**2 - (2/5)**2)
x

0.4

In [45]:
# 第二次大循环
# 是否拖欠贷款
gini = 1-(3/6)**2-(3/6)**2
gini

0.5

In [47]:
# 是否有房
gini_in = 2/6*0+4/6*(1-(3/4)**2-(1/4)**2)
gini_in

0.25

In [48]:
# 年收入属性 77.5
x = 1/6*0+5/6*(1-(3/5)**2 - (2/5)**2)
x

0.4

In [53]:
# 年收入属性87.5
x = 2/6*(1-(1/2)**2-(1/2)**2) + 4/6*(1-(2/4)**2-(2/4)**2)
x

0.5

In [54]:
# 年收入属性92.5
x = 3/6*(1-(1/3)**2-(2/3)**2) + 3/6*(1-(1/3)**2-(2/3)**2)
x

0.4444444444444444

In [55]:
x = 8/10*(1-(5/8)**2-(3/8)**2)
x

0.375

In [56]:
# 年收入属性110
x = 4/6*(1-(1/4)**2-(3/4)**2) + 2/6*(1-(2/2)**2)
x

0.25

In [57]:
# 年收入属性172.5
x = 5/6*(1-(2/5)**2-(3/5)**2) + 1/6*0
x

0.4

# 特征提取-特征工程
- 字典特征提取

```

作用：对字典数据进行特征值化

sklearn.feature_extraction.DictVectorizer(sparse=True,…)
DictVectorizer.fit_transform(X)
X:字典或者包含字典的迭代器返回值
返回sparse矩阵
DictVectorizer.get_feature_names() 返回类别名称
```

In [2]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import jieba


[{'city': '北京', 'temperature': 100},
 {'city': '上海', 'temperature': 60},
 {'city': '深圳', 'temperature': 30}]

In [3]:
# 构造数据
# 数据
data = [{'city': '北京','temperature':100},
{'city': '上海','temperature':60},
{'city': '深圳','temperature':30}]

In [5]:
# 实例化api
transfer = DictVectorizer(sparse=False)

In [6]:
mydata = transfer.fit_transform(data)

In [7]:
print("转化后\n",mydata)
print("特征名\n",transfer.get_feature_names())

转化后
 [[  0.   1.   0. 100.]
 [  1.   0.   0.  60.]
 [  0.   0.   1.  30.]]
特征名
 ['city=上海', 'city=北京', 'city=深圳', 'temperature']


In [10]:
data = ["life life is short,i like python",
"life is too long,i dislike python"]

In [8]:
transfer = CountVectorizer(stop_words=['is'])

In [11]:
mydata = transfer.fit_transform(data)

In [12]:
print(mydata.toarray())
print(transfer.get_feature_names())

[[0 2 1 0 1 1 0]
 [1 1 0 1 1 0 1]]
['dislike', 'life', 'like', 'long', 'python', 'short', 'too']


# 中文文本提取

In [13]:
data = ["一种还是一种今天很残酷，明天更残酷，后天很美好，但绝对大部分是死在明天晚上，所以每个人不要放弃今天。",
            "我们看到的从很远星系来的光是在几百万年之前发出的，这样当我们看到宇宙时，我们是在看它的过去。",
            "如果只用一种方式了解某样事物，你就不会真正了解它。了解事物真正含义的秘密取决于如何将其与我们所了解的事物相联系。"]


In [21]:
test_list = []

In [22]:
# 定义切割函数
def word_cut(text):
    return " ".join(list(jieba.cut(text)))

In [23]:
for i in data:
    test_list.append(word_cut(i))

In [24]:
test_list

['一种 还是 一种 今天 很 残酷 ， 明天 更 残酷 ， 后天 很 美好 ， 但 绝对 大部分 是 死 在 明天 晚上 ， 所以 每个 人 不要 放弃 今天 。',
 '我们 看到 的 从 很 远 星系 来 的 光是在 几百万年 之前 发出 的 ， 这样 当 我们 看到 宇宙 时 ， 我们 是 在 看 它 的 过去 。',
 '如果 只用 一种 方式 了解 某样 事物 ， 你 就 不会 真正 了解 它 。 了解 事物 真正 含义 的 秘密 取决于 如何 将 其 与 我们 所 了解 的 事物 相 联系 。']

In [25]:
transfer = CountVectorizer(stop_words=["一种"])
mydata = transfer.fit_transform(test_list)
print(mydata.toarray()) # 矩阵
print(transfer.get_feature_names())

[[0 1 0 0 0 2 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 2 0 1 0 2 1 0 0 0 1 1 0 0 1 0]
 [0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 3 0 0 0 0 1 0 0 0 0 2 0 0 0 0 0 1 0 1]
 [1 0 0 4 3 0 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 2 1 0 0 1 0 0 0]]
['不会', '不要', '之前', '了解', '事物', '今天', '光是在', '几百万年', '发出', '取决于', '只用', '后天', '含义', '大部分', '如何', '如果', '宇宙', '我们', '所以', '放弃', '方式', '明天', '星系', '晚上', '某样', '残酷', '每个', '看到', '真正', '秘密', '绝对', '美好', '联系', '过去', '还是', '这样']
